import { existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { isGuidesFlagOn } from "./lib/guides/guidesFlag.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));

// Build-time guard: the SC2 icon library must be present for the Icon
// primitive to resolve names. Phase 0 copies icons from
// reveal-sc2-opponent-main/SC2-Overlay/icons/ into public/icons/sc2/.
const iconsDir = join(__dirname, "public", "icons", "sc2");
if (!existsSync(iconsDir)) {
  throw new Error(
    `[next.config] Missing SC2 icon directory at ${iconsDir}. ` +
      `Run the icon copy step or restore from reveal-sc2-opponent-main/SC2-Overlay/icons/.`,
  );
}

// Instant Analysis engine assets (generated by scripts/build-browser-engine.mjs).
// /pyodide/<version>/* and /engine/<version>/<bundleId>/* are versioned and
// content-addressed, so browsers may cache them forever; the tiny pointer
// /engine/current.json must always revalidate so a deploy switches bundles.
// The patterns do not overlap: the bundle pattern needs at least two segments
// after /engine/ (version + bundle id), the pointer has one.
const IMMUTABLE_CACHE = "public, max-age=31536000, immutable";
const engineAssetHeaders = [
  {
    source: "/pyodide/:path*",
    headers: [{ key: "Cache-Control", value: IMMUTABLE_CACHE }],
  },
  {
    source: "/engine/:version/:bundle/:file*",
    headers: [{ key: "Cache-Control", value: IMMUTABLE_CACHE }],
  },
  {
    source: "/engine/current.json",
    headers: [{ key: "Cache-Control", value: "no-cache" }],
  },
];
/**
 * The old /meta radar page was replaced by the build guides. With guides
 * on (same NEXT_PUBLIC_GUIDES_ENABLED parsing as lib/guides/flags.ts),
 * /meta is a permanent redirect to /guides; with guides off it points
 * home temporarily, so search engines don't learn a destination that
 * may change once the flag flips. Read at build time, like the inlined
 * NEXT_PUBLIC_* value the pages use.
 *
 * @param {boolean} guidesOn
 * @returns {Array<{ source: string, destination: string, permanent: boolean }>}
 */
function metaRedirects(guidesOn) {
  const destination = guidesOn ? "/guides" : "/";
  const fallbacks = ["/meta", "/meta/:path*"].map((source) => ({ source, destination, permanent: guidesOn }));
  return guidesOn ? [...metaMatchupRedirects(), ...fallbacks] : fallbacks;
}

/** The nine matchups (lib/guides/slugs.ts GUIDE_MATCHUPS; a test keeps them equal). */
const META_REDIRECT_MATCHUPS = ["PvP", "PvT", "PvZ", "TvP", "TvT", "TvZ", "ZvP", "ZvT", "ZvZ"];

/**
 * Case-insensitive pattern for a `has` value (Next anchors it):
 * "PvZ" → "[Pp][Vv][Zz]".
 *
 * @param {string} text
 * @returns {string}
 */
function anyCase(text) {
  return [...text].map((ch) => `[${ch.toUpperCase()}${ch.toLowerCase()}]`).join("");
}

/**
 * Old radar links carried the matchup in the query
 * ("/meta?axis=league&band=4&matchup=PvZ"): send each straight to its
 * matchup guide ("/guides/pvz", lowercase, in one hop) ahead of the
 * generic /meta → /guides rule. Next passes the old query through; the
 * guide page ignores parameters it doesn't know.
 *
 * @returns {Array<{ source: string, has: Array<{ type: "query", key: string, value: string }>, destination: string, permanent: boolean }>}
 */
function metaMatchupRedirects() {
  return META_REDIRECT_MATCHUPS.map((matchup) => ({
    source: "/meta",
    has: [{ type: "query", key: "matchup", value: anyCase(matchup) }],
    destination: `/guides/${matchup.toLowerCase()}`,
    permanent: true,
  }));
}

/**
 * The Build adapter (/optimizer) was removed in July 2026, but Google kept
 * ranking its URL. Its closest living successor is the build-order guides,
 * so the old URL passes its ranking there with a permanent redirect while
 * guides are on, and points home temporarily while they are off (same
 * reasoning as the /meta rules above).
 *
 * @param {boolean} guidesOn
 * @returns {Array<{ source: string, destination: string, permanent: boolean }>}
 */
function retiredToolRedirects(guidesOn) {
  const destination = guidesOn ? "/guides" : "/";
  return ["/optimizer", "/optimizer/:path*"].map((source) => ({ source, destination, permanent: guidesOn }));
}

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  poweredByHeader: false,
  // transformers.js (on-device chat translation) is browser-only for
  // us — loaded via dynamic import inside client code. Keep it out of
  // the server bundle so webpack never tries to compile its Node-side
  // sharp/onnxruntime-node requires.
  serverExternalPackages: ["@xenova/transformers"],
  async redirects() {
    const guidesOn = isGuidesFlagOn(process.env.NEXT_PUBLIC_GUIDES_ENABLED);
    return [...metaRedirects(guidesOn), ...retiredToolRedirects(guidesOn)];
  },
  // Tighten the cache for the analyzer page so it always reflects the
  // user's latest data, but let the marketing routes use Vercel's edge.
  async headers() {
    return [
      {
        source: "/app/:path*",
        headers: [{ key: "Cache-Control", value: "no-store" }],
      },
      {
        source: "/devices",
        headers: [{ key: "Cache-Control", value: "no-store" }],
      },
      ...engineAssetHeaders,
    ];
  },
};

export default nextConfig;
