/**
 * Convert an OptimizeResult into the payload for the existing custom
 * builds API: PUT /v1/custom-builds/:slug (see BuildEditorSheet for
 * the canonical manual flow and apps/api validation/customBuild.js
 * for the accepted schema).
 */
import {
  eventsToSignature,
  formatBuildTime,
  normalizeBuildEvents,
  slugifyBuildName,
  type BuildSignatureItem,
} from "@/lib/build-events";
import type { Race, VsRace } from "@/lib/race";
import { buildOrderText } from "../sim/format";
import type { OptimizeResult } from "../types";

export interface CustomBuildPayload {
  slug: string;
  name: string;
  race: Race;
  vsRace: VsRace;
  description?: string;
  notes?: string;
  isPublic: boolean;
  signature: BuildSignatureItem[];
  perspective: "you";
}

export function defaultBuildName(result: OptimizeResult): string {
  const objective =
    result.objective.id === "earliest-safe-expansion"
      ? "safe expand"
      : result.objective.id === "max-workers-at-t"
        ? "greedy eco"
        : "army timing";
  return `Optimized ${objective} (${result.profileId})`;
}

function describeSafety(result: OptimizeResult): string {
  if (result.safety.threats.length === 0) {
    return "No threats selected.";
  }
  const lines = result.safety.threats.map((t) => {
    const margin = Math.round(t.worstMargin * 100);
    return `- ${t.threatName}: ${t.verdict} (worst margin ${margin >= 0 ? "+" : ""}${margin}%)`;
  });
  return lines.join("\n");
}

/**
 * Notes carry the full supply-stamped build order plus provenance —
 * everything needed to re-run or audit the optimization later.
 */
export function buildNotes(result: OptimizeResult): string {
  const sections = [
    "Generated by the build optimizer.",
    "",
    "Build order:",
    buildOrderText(result.sim),
    "",
    "Safety report:",
    describeSafety(result),
    "",
    `Patch profile: ${result.profileId}`,
    `Objective: ${result.objective.id}`,
    `Seed: ${result.seed} · generations: ${result.generations} · evaluations: ${result.evaluations}`,
    `Workers at ${formatBuildTime(result.sim.endTime)}: ${result.sim.finalWorkers}`,
  ];
  return sections.join("\n").slice(0, 8000);
}

export function toCustomBuildPayload(
  result: OptimizeResult,
  options: {
    name: string;
    vsRace: VsRace;
    description?: string;
    isPublic?: boolean;
  },
): CustomBuildPayload {
  const slug = slugifyBuildName(options.name);
  // Reuse the exact signature-compression path manual builds use so
  // the agent's classifier sees identical shapes.
  const rows = normalizeBuildEvents(
    result.sim.steps
      .filter((s) => !["Probe", "SCV", "Drone"].includes(s.name))
      .map((s) => ({ time: Math.max(0, Math.round(s.startSec)), name: s.name })),
  );
  const signature = eventsToSignature(rows);
  return {
    slug,
    name: options.name.trim().slice(0, 120),
    race: result.sim.race,
    vsRace: options.vsRace,
    description: options.description?.trim().slice(0, 4000) || undefined,
    notes: buildNotes(result),
    isPublic: options.isPublic ?? false,
    signature,
    perspective: "you",
  };
}

export const CUSTOM_BUILD_PUT_PATH = (slug: string): string =>
  `/v1/custom-builds/${encodeURIComponent(slug)}`;
