"""Replay-observed control-group membership, without replay-specific unit IDs.

SC2 selection buffers are reconstructed independently because sc2reader 1.8's
optional SelectionTracker does not implement steals and mishandles OneIndices.
Names are resolved at the event frame, never from a unit's final morphed type.
Physical number keys/custom bindings are not part of the replay protocol.
"""

from __future__ import annotations

import math
from collections import Counter
from collections.abc import Mapping
from typing import Any

OPENING_SECONDS = 60
_ASSIGNMENTS = {"set", "add", "stealSet", "stealAdd"}
_MAX_TYPES = 8
_MAX_SELECTION = 4096


def _integer(value: Any) -> int | None:
    return value if isinstance(value, int) and not isinstance(value, bool) else None


def _name(value: Any) -> str | None:
    value = getattr(value, "name", None)
    if not isinstance(value, str):
        return None
    clean = " ".join(value.split())
    return clean[:64] if clean else None


def _deselect(selection: list[int] | None, mode: Any, data: Any) -> tuple[list[int] | None, bool]:
    """Apply replay masks to sorted buffers; an invalid buffer remains unknown.

    ZeroIndices contains the indices to *retain*, OneIndices those to remove.
    A full clear can recover an unknown buffer. Applying a partial mask cannot.
    """
    if mode == "None":
        return (list(selection) if selection is not None else None), False
    if mode not in ("Mask", "OneIndices", "ZeroIndices") or not isinstance(data, (list, tuple)):
        return None, True
    if mode == "ZeroIndices" and not data:
        return [], False
    if selection is None:
        return None, False
    if mode == "Mask":
        if len(data) > len(selection) or any(not isinstance(bit, (bool, int)) or bit not in (0, 1) for bit in data):
            return None, True
        return [unit_id for index, unit_id in enumerate(selection) if index >= len(data) or not data[index]], False
    if any(_integer(index) is None or index < 0 or index >= len(selection) for index in data) or len(set(data)) != len(data):
        return None, True
    indices = set(data)
    return [unit_id for index, unit_id in enumerate(selection) if (index in indices) == (mode == "ZeroIndices")], False


def _counts(counter: Counter, limit: int = _MAX_TYPES) -> list[dict]:
    return [{"name": name, "count": count} for name, count in sorted(counter.items(), key=lambda item: (-item[1], item[0]))[:limit]]


def steal_housekeeping_event_ids(events: Any, *, opponent_pid: int) -> set[int]:
    """Recognize complete automatic buffer transactions generated by a steal.

    SC2 emits same-frame recall/(deselect)/set-or-clear/selection-restore
    transactions for other buffers after a steal. They are bookkeeping, not
    additional recalls or assignments made by the player. Removing units at
    the steal and replaying these deltas would remove them twice. A standalone
    same-frame recall is deliberately retained: it could be another input.

    See https://github.com/ggtracker/sc2reader/issues/183 for the producer's
    documented sequence. Recognize complete transactions, never entire frames.
    """
    from .play_signature import _slot, control_group_action, event_pid

    # Camera observations can interleave the generated transaction. They are
    # still retained by the behavior extractor; they only disappear from this
    # pattern-recognition view of the stream.
    player_events = [event for event in events if event_pid(event) == opponent_pid
                     and not any(base.__name__.lower() in ("cameraevent", "playerstatsevent") for base in type(event).__mro__)]
    hidden: set[int] = set()

    def selection(event: Any) -> bool:
        return getattr(event, "control_group", None) == 10 and any(base.__name__.lower() == "selectionevent" for base in type(event).__mro__)

    for index, event in enumerate(player_events):
        if control_group_action(event) not in ("stealSet", "stealAdd"):
            continue
        frame, destination = getattr(event, "frame", None), _slot(event)
        if frame is None or destination is None:
            continue
        cursor = index + 1
        while cursor < len(player_events):
            recall = player_events[cursor]
            other = _slot(recall)
            if getattr(recall, "frame", None) == frame and control_group_action(recall) == "clear" and other is not None and other != destination:
                hidden.add(id(recall))
                cursor += 1
                continue
            if getattr(recall, "frame", None) != frame or control_group_action(recall) != "recall" or other is None or other == destination:
                break
            end = cursor + 1
            # An optional active-selection delta precedes the buffer write.
            if end + 1 < len(player_events) and selection(player_events[end]) and _slot(player_events[end + 1]) == other and control_group_action(player_events[end + 1]) in ("set", "clear"):
                end += 1
            if end < len(player_events) and _slot(player_events[end]) == other and control_group_action(player_events[end]) in ("set", "clear"):
                end += 1
            if end >= len(player_events) or not selection(player_events[end]):
                break
            restore = player_events[end]
            new_ids = getattr(restore, "new_unit_ids", None)
            if not isinstance(new_ids, (list, tuple)) or not new_ids or any(getattr(item, "frame", None) != frame for item in player_events[cursor:end + 1]):
                break
            hidden.update(id(item) for item in player_events[cursor:end + 1])
            cursor = end + 1
    return hidden


class _Membership:
    def __init__(self, replay: Any):
        self.replay = replay
        self.buffers: dict[int, list[int] | None] = {slot: [] for slot in range(11)}
        self.objects = dict(getattr(replay, "objects", {}) or {})
        self.observed_types: dict[int, tuple[float, str]] = {}
        self.assignments = self.decoded = self.errors = 0
        self.slots: dict[int, dict] = {}
        self.sequence: list[dict] = []
        self.sequence_seen: set[tuple] = set()
        self.shared: dict[tuple[int, int], dict] = {}

    def _selection(self, event: Any, slot: int, frame: float) -> None:
        selection, error = _deselect(self.buffers[slot], getattr(event, "mask_type", None), getattr(event, "mask_data", None))
        self.errors += int(error)
        new_ids = getattr(event, "new_unit_ids", None)
        new_units = getattr(event, "new_units", None)
        if new_units is None:
            new_units = getattr(event, "objects", None)
        if new_ids is None and isinstance(new_units, (list, tuple)):
            new_ids = [getattr(unit, "id", None) for unit in new_units]
        if not isinstance(new_ids, (list, tuple)) or len(new_ids) > _MAX_SELECTION or any(_integer(unit_id) is None or unit_id <= 0 for unit_id in new_ids):
            self.buffers[slot] = None
            self.errors += 1
            return
        if isinstance(new_units, (list, tuple)):
            for unit in new_units:
                unit_id = _integer(getattr(unit, "id", None))
                if unit_id is not None and unit_id > 0:
                    self.objects[unit_id] = unit
        # The numeric unit link in a selection is itself time-specific evidence.
        # It also supports old replays that have no tracker history.
        unit_types = getattr(getattr(self.replay, "datapack", None), "units", {})
        info = getattr(event, "new_unit_info", ()) or ()
        if isinstance(unit_types, Mapping) and isinstance(info, (list, tuple)):
            for item in info:
                if isinstance(item, (list, tuple)) and len(item) >= 2:
                    unit_id, type_id = _integer(item[0]), _integer(item[1])
                    name = _name(unit_types.get(type_id))
                    if unit_id in new_ids and name:
                        self.observed_types[unit_id] = (frame, name)
        if selection is not None:
            selection = sorted(set(selection).union(new_ids))
            if len(selection) > _MAX_SELECTION:
                selection = None
                self.errors += 1
        self.buffers[slot] = selection

    def _unit_name(self, unit_id: int, frame: float) -> str | None:
        unit = self.objects.get(unit_id)
        history = getattr(unit, "type_history", None)
        latest_frame, latest_name = -math.inf, None
        if isinstance(history, Mapping):
            for at_frame, unit_type in history.items():
                if isinstance(at_frame, (int, float)) and not isinstance(at_frame, bool) and math.isfinite(at_frame) and latest_frame <= at_frame <= frame:
                    name = _name(unit_type)
                    if name:
                        latest_frame, latest_name = at_frame, name
        observed = self.observed_types.get(unit_id)
        if observed is not None and latest_frame < observed[0] <= frame:
            latest_name = observed[1]
        return latest_name

    def _living(self, selection: list[int], frame: float) -> list[int]:
        # Keep buffer indices intact until their actual replay delta arrives.
        # Dead units are excluded only when observing membership, never before
        # applying a mask to the internal selection buffer.
        result = []
        for unit_id in selection:
            died = getattr(self.objects.get(unit_id), "died_at", None)
            if not isinstance(died, (int, float)) or isinstance(died, bool) or not math.isfinite(died) or died > frame:
                result.append(unit_id)
        return result

    def _composition(self, selection: list[int] | None, frame: float) -> tuple[Counter, list[int]] | None:
        if selection is None:
            return None
        living = self._living(selection, frame)
        names = [self._unit_name(unit_id, frame) for unit_id in living]
        if any(name is None for name in names):
            return None
        return Counter(names), living

    def _observe(self, slot: int, action: str, sec: float, frame: float) -> None:
        selection = self.buffers[10 if action == "recall" else slot]
        composition = self._composition(selection, frame)
        if composition is None:
            return
        types, _ = composition
        if action in _ASSIGNMENTS:
            self.decoded += 1
        if not types:
            return
        at_sec = round(sec, 3)
        snapshot = {"slot": slot, "action": action, "atSec": at_sec, "units": _counts(types)}
        if action in _ASSIGNMENTS:
            row = self.slots.setdefault(slot, {"slot": slot, "assignments": 0, "unitTypes": Counter(),
                                              "firstAssignment": {key: value for key, value in snapshot.items() if key != "slot"}})
            row["assignments"] += 1
            row["unitTypes"].update(types.keys())
        sequence_key = (slot, action, tuple(sorted(types.items())))
        if sec <= OPENING_SECONDS and len(self.sequence) < 24 and sequence_key not in self.sequence_seen:
            self.sequence.append(snapshot)
            self.sequence_seen.add(sequence_key)
        if action not in _ASSIGNMENTS:
            return
        # Evaluate only pairs changed by this assignment. Steals have already
        # removed the selected identities from other groups at this point.
        if self.buffers[slot] is None:
            return
        selected = set(self._living(self.buffers[slot], frame))
        for other in range(10):
            if other == slot or self.buffers[other] is None:
                continue
            common = selected.intersection(self._living(self.buffers[other], frame))
            known = [(unit_id, self._unit_name(unit_id, frame)) for unit_id in common]
            known = [(unit_id, name) for unit_id, name in known if name]
            if not known:
                continue
            pair = tuple(sorted((slot, other)))
            shared = self.shared.setdefault(pair, {"slots": list(pair), "firstAtSec": at_sec, "units": {}})
            for unit_id, name in known:
                shared["units"].setdefault(name, set()).add(unit_id)

    def consume(self, event: Any, *, sec: float, frame: float, action: str | None, slot: int | None) -> None:
        names = tuple(base.__name__.lower() for base in type(event).__mro__)
        if "selectionevent" in names:
            selection_slot = _integer(getattr(event, "control_group", None))
            if selection_slot is not None and 0 <= selection_slot <= 10:
                self._selection(event, selection_slot, frame)
            return
        if slot is None:
            return
        if action is None:
            if any("controlgroup" in name for name in names):
                # A future update could have cross-group effects (as steals
                # do), so retaining any membership would be speculative.
                self.buffers = {index: None for index in range(11)}
                self.errors += 1
            return
        if action == "clear":
            self.buffers[slot] = []
            return
        if action == "recall":
            self.buffers[10], error = _deselect(self.buffers[slot], getattr(event, "mask_type", None), getattr(event, "mask_data", None))
            self.errors += int(error)
        elif action in _ASSIGNMENTS:
            self.assignments += 1
            selected = self.buffers[10]
            if action in ("set", "stealSet"):
                self.buffers[slot] = list(selected) if selected is not None else None
            else:
                existing, error = _deselect(self.buffers[slot], getattr(event, "mask_type", None), getattr(event, "mask_data", None))
                self.errors += int(error)
                self.buffers[slot] = sorted(set(existing).union(selected)) if existing is not None and selected is not None else None
            if action in ("stealSet", "stealAdd"):
                for other in range(10):
                    if other == slot:
                        continue
                    previous = self.buffers[other]
                    if selected is None:
                        # An unknown active selection could remove any member.
                        self.buffers[other] = [] if previous == [] else None
                    elif previous is not None:
                        stolen = set(selected)
                        self.buffers[other] = [unit_id for unit_id in previous if unit_id not in stolen]
        self._observe(slot, action, sec, frame)

    def result(self) -> dict:
        if not self.assignments or max(self.assignments, self.decoded, self.errors) > 99999:
            return {}
        result: dict = {"membershipCoverage": {"assignments": self.assignments, "decodedAssignments": self.decoded, "selectionErrors": self.errors}}
        if self.slots:
            result["unitAssignments"] = [{**row, "unitTypes": _counts(row["unitTypes"])} for _, row in sorted(self.slots.items())]
        if self.sequence:
            result["openingSequence"] = self.sequence
        if self.shared and all(len(ids) <= 99999 for row in self.shared.values() for ids in row["units"].values()):
            result["sharedAssignments"] = [{"slots": row["slots"], "firstAtSec": row["firstAtSec"],
                                             "unitTypes": _counts(Counter({name: len(ids) for name, ids in row["units"].items()}), 6)}
                                            for _, row in sorted(self.shared.items())]
        return result


def extract_group_membership_signature(replay: Any, *, opponent_pid: Any, game_length_sec: Any) -> dict:
    """Return bounded fields to merge into a behavior signature's controlGroups.

    unitTypes on each slot counts assignments containing a type. A first-
    assignment snapshot counts actual units. Shared pairs count distinct units
    observed in both buffers at once. No unit IDs leave this function.
    """
    from .play_signature import _clock, _slot, control_group_action, event_pid, event_seconds

    if replay is None or isinstance(opponent_pid, bool):
        return {}
    try:
        target_pid = int(opponent_pid)
    except (TypeError, ValueError, OverflowError):
        return {}
    if target_pid <= 0:
        return {}
    events = getattr(replay, "events", None)
    if events is None:
        return {}
    fps, active_seconds = _clock(replay, game_length_sec)
    tracker = _Membership(replay)
    housekeeping = steal_housekeeping_event_ids(events, opponent_pid=target_pid)
    for event in events:
        if event_pid(event) != target_pid or id(event) in housekeeping:
            continue
        sec = event_seconds(event, fps)
        if sec is None or sec < 0 or sec > active_seconds:
            continue
        raw_frame = getattr(event, "frame", None)
        frame = float(raw_frame) if raw_frame is not None else sec * fps
        tracker.consume(event, sec=sec, frame=frame, action=control_group_action(event), slot=_slot(event))
    return tracker.result()
