"""Bounded replay-observable behavior for private candidate matching.

This describes logical commands, not physical keys, mouse clicks or bindings.
Selection and camera records may also be generated by the game. Their counts
are deliberately labelled observations, never keystrokes or effective APM.
"""

from __future__ import annotations

import math
from collections import Counter
from collections.abc import Mapping
from typing import Any

WINDOW_SEC = 600
PHASES = ((0, 120), (120, 300), (300, 600))
# Upper-inclusive real-second bins, followed by the overflow bin. Zero-frame
# intervals are observations too; they must not disappear from the cadence.
INTERVAL_BOUNDS = (0.15, 0.35, 0.65, 1.5, 4.0)
_GROUP_ACTIONS = ("set", "add", "recall", "stealSet", "stealAdd", "clear")


def _names(event: Any) -> tuple[str, ...]:
    return tuple(base.__name__.lower() for base in type(event).__mro__)


def event_pid(event: Any) -> int | None:
    """Use canonical Player.pid, never override it with a protocol user id."""
    player = getattr(event, "player", None)
    if player is not None:
        value = getattr(player, "pid", None)
        return value if isinstance(value, int) and not isinstance(value, bool) and value > 0 else None
    # Unresolved sc2reader GameEvent.pid is a zero-based protocol user id.
    # Without the attached player it cannot safely be used as Player.pid.
    if any(base.__module__.startswith("sc2reader.events") for base in type(event).__mro__):
        return None
    value = getattr(event, "pid", None)
    return value if isinstance(value, int) and not isinstance(value, bool) and value > 0 else None


def event_seconds(event: Any, fps: float) -> float | None:
    frame = getattr(event, "frame", None)
    try:
        value = float(frame) / fps if frame is not None else float(getattr(event, "second", None)) * 16.0 / fps
    except (TypeError, ValueError, OverflowError, ZeroDivisionError):
        return None
    return value if math.isfinite(value) else None


def control_group_action(event: Any) -> str | None:
    """Decode both sc2reader 1.8 generic and 1.9 concrete event shapes.

    Upstream sc2reader/events/game.py identifies 4/5 as set/add with steal;
    3 is the automatically generated delete when a group is emptied by steal.
    Numeric semantics take precedence: 1.9 uses Set/Add subclasses for steals.
    """
    names = _names(event)
    if not any("controlgroup" in name for name in names):
        return None
    update = getattr(event, "update_type", getattr(event, "control_group_update", None))
    if update is not None:
        if isinstance(update, bool):
            return None
        try:
            return {0: "set", 1: "add", 2: "recall", 3: "clear", 4: "stealSet", 5: "stealAdd"}.get(int(update))
        except (TypeError, ValueError, OverflowError):
            return None
    for name in names:
        if "addtocontrolgroup" in name:
            return "add"
        if "setcontrolgroup" in name:
            return "set"
        if "getcontrolgroup" in name:
            return "recall"
        if "deletecontrolgroup" in name:
            return "clear"
    return None


def _slot(event: Any) -> int | None:
    value = getattr(event, "control_group", getattr(event, "control_group_index", None))
    if isinstance(value, bool):
        return None
    try:
        slot = int(value)
    except (TypeError, ValueError, OverflowError):
        return None
    return slot if 0 <= slot <= 9 else None


def _clock(replay: Any, game_length_sec: Any) -> tuple[float, int]:
    fps, length = 22.4, None
    try:
        from core.timebase import infer_fps, real_game_length
        inferred = float(infer_fps(replay))
        if math.isfinite(inferred) and inferred > 0:
            fps = inferred
        measured = float(real_game_length(replay))
        if math.isfinite(measured) and measured > 0:
            length = measured
    except (ImportError, AttributeError, TypeError, ValueError, OverflowError, ZeroDivisionError):
        pass
    if length is None:
        # The agent may be imported without the replay-engine on sys.path.
        # Resolve from the same header fields before using ctx's legacy clock.
        try:
            frames = float(getattr(replay, "frames", 0))
            seconds = float(getattr(getattr(replay, "length", None), "seconds", 0))
            if frames > 0 and seconds > 0 and 14 <= frames / seconds <= 24:
                fps = frames / seconds
                length = frames / fps
            elif frames > 0 and math.isfinite(frames):
                length = frames / fps
        except (TypeError, ValueError, OverflowError, ZeroDivisionError):
            pass
    if length is None:
        try:
            length = float(game_length_sec)
        except (TypeError, ValueError, OverflowError):
            length = WINDOW_SEC
    if not math.isfinite(length) or length <= 0:
        length = WINDOW_SEC
    return fps, min(WINDOW_SEC, max(1, math.ceil(length)))


def _histogram_add(histogram: list[int], interval: float) -> None:
    if interval < 0 or not math.isfinite(interval):
        return
    bucket = next((i for i, upper in enumerate(INTERVAL_BOUNDS) if interval <= upper + 1e-9), 5)
    histogram[bucket] = min(99999, histogram[bucket] + 1)


def _new_group(slot: int) -> dict:
    return {"slot": slot, **{name: 0 for name in _GROUP_ACTIONS}}


def _increment_group(row: dict, action: str) -> None:
    row[action] += 1
    if action in ("stealSet", "stealAdd"):
        ordinary = "set" if action == "stealSet" else "add"
        row[ordinary] += 1


def _ability_name(event: Any) -> str | None:
    raw = getattr(event, "ability_name", None) or getattr(getattr(event, "ability", None), "name", None)
    if not isinstance(raw, str):
        return None
    name = " ".join(raw.split())[:64]
    return name or None


def _top_counts(counts: Counter, limit: int) -> list[dict]:
    return [{"name": name, "count": min(99999, count)} for name, count in sorted(counts.items(), key=lambda item: (-item[1], item[0]))[:limit]]


def extract_behavior_signature(replay: Any, *, opponent_pid: Any, game_length_sec: Any) -> dict:
    """One pass over decoded events; fixed-size timing and group aggregates.

    Only the first full command within two seconds after a recall is associated
    with that slot. Any intervening selection/group update invalidates that
    association. Ability names are decoded evidence, never guessed unit roles.
    """
    if isinstance(opponent_pid, bool):
        return {}
    try:
        target_pid = int(opponent_pid)
    except (TypeError, ValueError, OverflowError):
        return {}
    if replay is None or target_pid <= 0:
        return {}
    events = getattr(replay, "events", None)
    if events is None:
        return {}
    fps, active_seconds = _clock(replay, game_length_sec)
    groups: dict[int, dict] = {}
    group_phases = [{"startSec": start, "endSec": min(end, active_seconds), "events": 0, "slots": {}} for start, end in PHASES if start < active_seconds]
    action_phases = [{"startSec": phase["startSec"], "endSec": phase["endSec"], "commands": 0, "selectionChanges": 0, "cameraMoves": 0, "controlGroups": 0} for phase in group_phases]
    actions = {"activeSeconds": active_seconds, "events": 0, "commands": 0, "selectionChanges": 0, "cameraMoves": 0, "queuedCommands": 0, "repeatCommands": 0,
               "targetCommands": {"none": 0, "point": 0, "unit": 0, "data": 0}}
    intervals, camera_intervals, recall_intervals = [0] * 6, [0] * 6, [0] * 6
    last_action = last_camera = last_recall = last_command = None
    last_recall_slot = last_command_key = pending_recall = None
    last_slot_recall: dict[int, float] = {}
    transitions: Counter = Counter()
    abilities: Counter = Counter()
    followups: dict[int, dict] = {}
    total_group_events = 0

    for event in events:
        if event_pid(event) != target_pid:
            continue
        sec = event_seconds(event, fps)
        if sec is None or sec < 0 or sec > active_seconds:
            continue
        phase_index = 0 if sec < 120 else 1 if sec < 300 else 2
        phase_index = min(phase_index, len(group_phases) - 1)
        group_phase, action_phase = group_phases[phase_index], action_phases[phase_index]
        names = _names(event)
        action = control_group_action(event)
        cadence_event = False
        if action is not None:
            slot = _slot(event)
            if slot is None:
                pending_recall = None
                continue
            row = groups.setdefault(slot, {**_new_group(slot), "doubleTap": 0, "firstUseSec": min(WINDOW_SEC, round(sec)), "recallIntervals": [0] * 6})
            _increment_group(row, action)
            _increment_group(group_phase["slots"].setdefault(slot, _new_group(slot)), action)
            group_phase["events"] += 1
            total_group_events += 1
            if action == "recall":
                if last_recall is not None:
                    gap = sec - last_recall
                    _histogram_add(recall_intervals, gap)
                    if last_recall_slot == slot and pending_recall == (slot, last_recall) and 0 <= gap <= .65:
                        row["doubleTap"] = min(9999, row["doubleTap"] + 1)
                    if last_recall_slot != slot and 0 <= gap <= 4:
                        transitions[(last_recall_slot, slot)] += 1
                if slot in last_slot_recall:
                    _histogram_add(row["recallIntervals"], sec - last_slot_recall[slot])
                last_slot_recall[slot], last_recall, last_recall_slot = sec, sec, slot
                pending_recall = (slot, sec)
            else:
                pending_recall = None
            if action != "clear":
                action_phase["controlGroups"] += 1
                cadence_event = True
                actions["events"] += 1
        elif "selectionevent" in names:
            # Group-buffer deltas are frequently automatic. Neither automatic
            # deltas nor active selection changes establish command attribution.
            pending_recall = None
            if getattr(event, "control_group", None) == 10:
                actions["selectionChanges"] += 1
                action_phase["selectionChanges"] += 1
                actions["events"] += 1
        elif "cameraevent" in names:
            actions["cameraMoves"] += 1
            action_phase["cameraMoves"] += 1
            actions["events"] += 1
            if last_camera is not None:
                _histogram_add(camera_intervals, sec - last_camera)
            last_camera = sec
        elif "commandmanagerstateevent" in names:
            # These are separately decoded command repetitions. Do not infer
            # ability, queued status or group purpose from their preceding event.
            actions["repeatCommands"] += 1
            actions["commands"] += 1
            actions["events"] += 1
            action_phase["commands"] += 1
            pending_recall = None
            cadence_event = True
        elif any(name.startswith("updatetarget") for name in names):
            # Updates do not carry a newly decoded command identity.
            pending_recall = None
        elif "commandevent" in names or any(name in names for name in ("basiccommandevent", "targetpointcommandevent", "targetunitcommandevent", "datacommandevent")):
            actions["commands"] += 1
            actions["events"] += 1
            action_phase["commands"] += 1
            cadence_event = True
            flags = getattr(event, "flag", None)
            queued = isinstance(flags, Mapping) and flags.get("queued") is True
            if queued:
                actions["queuedCommands"] += 1
            target = {"None": "none", "TargetPoint": "point", "TargetUnit": "unit", "Data": "data"}.get(getattr(event, "ability_type", None))
            if target is not None:
                actions["targetCommands"][target] += 1
            ability = _ability_name(event)
            if ability:
                abilities[ability] += 1
            command_key = (getattr(event, "ability_id", None), target)
            rapid_repeat = command_key[0] is not None and command_key == last_command_key and last_command is not None and 0 <= sec - last_command <= .35
            if pending_recall is not None and 0 <= sec - pending_recall[1] <= 2:
                slot = pending_recall[0]
                followup = followups.setdefault(slot, {"slot": slot, "commands": 0, "queued": 0, "rapidRepeat": 0, "abilities": Counter()})
                followup["commands"] += 1
                followup["queued"] += int(queued)
                followup["rapidRepeat"] += int(rapid_repeat)
                if ability:
                    followup["abilities"][ability] += 1
            pending_recall = None
            last_command, last_command_key = sec, command_key
        elif any("controlgroup" in name for name in names):
            # Unknown protocol updates must not be guessed as recalls or leave
            # a preceding recall associated with a subsequent command.
            pending_recall = None
        if cadence_event:
            if last_action is not None:
                _histogram_add(intervals, sec - last_action)
            last_action = sec

    result: dict = {}
    # Never clip independent counts into mutually inconsistent evidence.
    # A pathological high-volume stream may exceed the storage contract; omit
    # that evidence family and retain the other independently observed family.
    groups_fit = total_group_events <= 99999 and all(
        row[name] <= 9999 for row in groups.values() for name in _GROUP_ACTIONS
    )
    if total_group_events and groups_fit:
        for row in groups.values():
            if not any(row["recallIntervals"]):
                del row["recallIntervals"]
        control = {"events": min(99999, total_group_events), "activeSeconds": active_seconds, "slots": [groups[slot] for slot in sorted(groups)]}
        control["phases"] = [{**phase, "events": min(99999, phase["events"]), "slots": [phase["slots"][slot] for slot in sorted(phase["slots"])]} for phase in group_phases]
        if transitions and max(transitions.values()) <= 9999:
            control["transitions"] = [{"from": pair[0], "to": pair[1], "count": min(9999, count)} for pair, count in sorted(transitions.items(), key=lambda item: (-item[1], item[0]))[:12]]
        if any(recall_intervals):
            control["recallIntervals"] = recall_intervals
        if followups:
            control["commandFollowup"] = [{**{key: min(99999, value) for key, value in row.items() if key != "abilities"}, "abilities": _top_counts(row["abilities"], 6)} for _, row in sorted(followups.items())]
        result["controlGroups"] = control
    if actions["events"] <= 99999 and (actions["commands"] or actions["selectionChanges"] or actions["cameraMoves"]):
        for name in ("events", "commands", "selectionChanges", "cameraMoves", "queuedCommands", "repeatCommands"):
            actions[name] = min(99999, actions[name])
        actions["targetCommands"] = {key: min(99999, value) for key, value in actions["targetCommands"].items()}
        actions["phases"] = [{key: min(99999, value) for key, value in phase.items()} for phase in action_phases]
        if any(intervals):
            actions["actionIntervals"] = intervals
        if any(camera_intervals):
            actions["cameraIntervals"] = camera_intervals
        if abilities:
            actions["abilityUsage"] = _top_counts(abilities, 12)
        result["actions"] = actions
    return result
