"use strict";

/**
 * Guide slugs — stable, per-matchup URL keys for the community build
 * guides (`/guides/<matchup>/<build>` and
 * `/guides/<matchup>/counter/<strategy>`), built once at require time from
 * the committed catalog `guideCatalog.json` (generated by apps/web
 * `npm run guides:catalog`; the API image does not ship apps/web).
 *
 * Two namespaces per matchup M = XvY (the uploading user's matchup):
 *
 *   - builds   — what the user can have as `myBuild`: catalog openers
 *                prefixed "XvY - …", plus the race-generic "<X race> - …"
 *                names when X is Terran or Zerg. Protoss users are only
 *                ever labelled "PvX - …", so PvX builds are PvX names only.
 *   - counters — what the opponent can have as `opponent.strategy`
 *                (labels are from the OPPONENT's point of view): openers
 *                prefixed "YvX - …" plus "<Y race> - …". Protoss opponents
 *                are only ever labelled "Protoss - …", so when Y is Protoss
 *                the namespace is the race-generic names only.
 *
 * Slug rule: the text after the first " - ", lowercased, every
 * non-alphanumeric run collapsed to "-", leading/trailing "-" trimmed.
 * When a matchup-prefixed name and a race-generic name collide in one
 * namespace, the matchup-prefixed name keeps the plain slug and the
 * race-generic one becomes "<race>-<slug>" (ZvP "2-base-nydus" →
 * "ZvP - 2 Base Nydus", "zerg-2-base-nydus" → "Zerg - 2 Base Nydus").
 * Any other collision throws at require time.
 *
 * `guideSlugs.lock.json` pins the resulting mapping; the jest test fails
 * when it drifts, so a catalog rename cannot silently break public URLs.
 * A deliberate rename adds the old slug to SLUG_ALIASES (resolved as a
 * redirect) and regenerates the lock (from apps/api):
 *
 *   node -e 'require("fs").writeFileSync("src/config/guideSlugs.lock.json",
 *     JSON.stringify(require("./src/config/guideSlugs").guideSlugTable(), null, 2) + "\n")'
 *
 * Pure and synchronous: no I/O after require, no logging.
 */

const GUIDE_CATALOG_JSON = require("./guideCatalog.json");

/**
 * @typedef {object} GuideCatalogEntry
 * @property {string} name        exact catalog name (join key with games)
 * @property {string} race        owning race ("Protoss" | "Terran" | "Zerg")
 * @property {string|null} matchup matchup for matchup-prefixed names, else null
 * @property {string} description detection rule prose
 * @property {boolean} opener     true when the definition can get a guide page
 */

/** @typedef {"builds"|"counters"} SlugKind */

/**
 * @typedef {object} SlugNamespace
 * @property {ReadonlyArray<string>} names catalog names, sorted
 * @property {Map<string, string>} bySlug  slug → catalog name
 * @property {Map<string, string>} byName  catalog name → slug
 */

/**
 * matchup slug → { oldSlug: liveSlug }.
 * @typedef {Readonly<Record<string, Readonly<Record<string, string>>>>} AliasTable
 */

/**
 * @typedef {object} ResolvedSlug
 * @property {string} matchup "PvZ" form
 * @property {string} name    exact catalog name
 * @property {string} slug    canonical slug
 */

/**
 * @typedef {object} SlugRedirect
 * @property {{ matchupSlug: string, slug: string }} redirect canonical location
 */

/** @typedef {Record<string, Record<string, string>>} SlugNamespaceTable */

/** Separator between a catalog name's prefix and its display text. */
const NAME_SEPARATOR = " - ";
/**
 * Appended to the display name of a race-generic entry whose slug got the
 * race prefix, so the two same-named guides of a namespace ("TvP - Widow
 * Mine Drop" / "Terran - Widow Mine Drop") never share a title or H1.
 */
const GENERIC_NAME_SUFFIX = " (any matchup)";
/** Upper bound on a slug's length (mirrors the web catalog's id cap). */
const SLUG_MAX_CHARS = 80;
/** Character offsets inside a "PvZ"-form matchup. */
const MY_RACE_INDEX = 0;
const OPP_RACE_INDEX = 2;
const PROTOSS_LETTER = "P";

/** The nine 1v1 matchups, user race first. */
const MATCHUPS = Object.freeze([
  "PvP", "PvT", "PvZ",
  "TvP", "TvT", "TvZ",
  "ZvP", "ZvT", "ZvZ",
]);

/** Race letter → the race word used by race-generic catalog names. */
const RACE_WORDS = Object.freeze(
  /** @type {Record<string, string>} */ ({ P: "Protoss", T: "Terran", Z: "Zerg" }),
);

/** @type {ReadonlyArray<SlugKind>} */
const SLUG_KINDS = Object.freeze(["builds", "counters"]);

/**
 * Retired slugs that must keep working, per kind and matchup slug:
 * `{ builds: { pvz: { "old-slug": "live-slug" } }, counters: { … } }`.
 * Targets must be live slugs (no chains); validated at require time.
 * Empty until a catalog rename needs one.
 * @type {Readonly<Record<SlugKind, AliasTable>>}
 */
const SLUG_ALIASES = Object.freeze({
  builds: Object.freeze({}),
  counters: Object.freeze({}),
});

/** @type {ReadonlyArray<string>} */
const EMPTY_NAMES = Object.freeze([]);

/**
 * Slugify free text with the guide rule. Diacritics are folded first
 * ("Pylône" → "pylone"); the ASCII catalog is unaffected.
 *
 * Example: `slugifyGuideText("Stargate into Glaives")` → "stargate-into-glaives".
 *
 * @param {string} text
 * @returns {string} possibly empty when the text has no ASCII letters/digits
 */
function slugifyGuideText(text) {
  return text
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, SLUG_MAX_CHARS)
    .replace(/-+$/, "");
}

/**
 * Human title of a catalog name: the text after the first " - ".
 *
 * Example: `displayName("PvZ - Stargate into Glaives")` → "Stargate into Glaives".
 *
 * @param {unknown} name
 * @returns {string} the name itself when it has no " - " separator ("" for non-strings)
 */
function displayName(name) {
  if (typeof name !== "string") return "";
  const at = name.indexOf(NAME_SEPARATOR);
  return at < 0 ? name : name.slice(at + NAME_SEPARATOR.length);
}

/**
 * Prefix of a catalog name: the text before the first " - ".
 *
 * @param {string} name
 * @returns {string|null}
 */
function namePrefix(name) {
  const at = name.indexOf(NAME_SEPARATOR);
  return at < 0 ? null : name.slice(0, at);
}

/**
 * Lowercase URL segment of a matchup.
 *
 * Example: `matchupSlug("PvZ")` → "pvz"; `matchupSlug("PvX")` → null.
 *
 * @param {string} matchup "PvZ" form
 * @returns {string|null}
 */
function matchupSlug(matchup) {
  return MATCHUPS.includes(matchup) ? matchup.toLowerCase() : null;
}

/** @type {ReadonlyMap<string, string>} lowercase slug → "PvZ" form */
const MATCHUP_BY_SLUG = new Map(MATCHUPS.map((m) => [m.toLowerCase(), m]));

/**
 * Matchup for a canonical (lowercase) matchup slug.
 *
 * Example: `matchupFromSlug("pvz")` → "PvZ"; `matchupFromSlug("PVZ")` → null.
 *
 * @param {unknown} slug
 * @returns {string|null}
 */
function matchupFromSlug(slug) {
  if (typeof slug !== "string") return null;
  return MATCHUP_BY_SLUG.get(slug) || null;
}

/**
 * Catalog-name prefixes that belong to one namespace of a matchup (see
 * the module comment for the perspective rules).
 *
 * @param {SlugKind} kind
 * @param {string} matchup "XvY"
 * @returns {{ matchupPrefix: string|null, raceWord: string|null }}
 */
function namespacePrefixes(kind, matchup) {
  const mine = matchup[MY_RACE_INDEX];
  const theirs = matchup[OPP_RACE_INDEX];
  if (kind === "builds") {
    return {
      matchupPrefix: matchup,
      raceWord: mine === PROTOSS_LETTER ? null : RACE_WORDS[mine],
    };
  }
  return {
    matchupPrefix: theirs === PROTOSS_LETTER ? null : `${theirs}v${mine}`,
    raceWord: RACE_WORDS[theirs],
  };
}

/**
 * Assign collision-free slugs to one namespace's names.
 *
 * @param {ReadonlyArray<string>} names sorted catalog names
 * @param {string|null} raceWord race word of the namespace's race-generic
 *   names (null when the namespace has none)
 * @param {string} label namespace label for error messages ("builds/zvp")
 * @returns {Map<string, string>} name → slug
 */
function assignSlugs(names, raceWord, label) {
  const plain = new Map(names.map((name) => [name, slugifyGuideText(displayName(name))]));
  const matchupOwned = new Set();
  for (const name of names) {
    if (namePrefix(name) !== raceWord) matchupOwned.add(plain.get(name));
  }
  const byName = new Map();
  const seen = new Map();
  for (const name of names) {
    const base = /** @type {string} */ (plain.get(name));
    const isGeneric = namePrefix(name) === raceWord;
    const slug = isGeneric && matchupOwned.has(base)
      ? slugifyGuideText(`${raceWord}-${base}`)
      : base;
    if (!slug || seen.has(slug)) {
      throw new Error(`guideSlugs: slug "${slug}" in ${label} is empty or collides (${seen.get(slug)} / ${name})`);
    }
    seen.set(slug, name);
    byName.set(name, slug);
  }
  return byName;
}

/**
 * Build one namespace from the catalog.
 *
 * @param {ReadonlyArray<GuideCatalogEntry>} catalog
 * @param {SlugKind} kind
 * @param {string} matchup
 * @returns {SlugNamespace}
 */
function buildNamespace(catalog, kind, matchup) {
  const { matchupPrefix, raceWord } = namespacePrefixes(kind, matchup);
  const names = catalog
    .filter((entry) => entry.opener)
    .map((entry) => entry.name)
    .filter((name) => {
      const prefix = namePrefix(name);
      return prefix !== null && (prefix === matchupPrefix || prefix === raceWord);
    })
    .sort();
  const label = `${kind}/${matchup.toLowerCase()}`;
  const byName = assignSlugs(names, raceWord, label);
  const bySlug = new Map([...byName].map(([name, slug]) => [slug, name]));
  return { names: Object.freeze(names), bySlug, byName };
}

/**
 * Every namespace, keyed by kind then "PvZ"-form matchup.
 *
 * @param {ReadonlyArray<GuideCatalogEntry>} catalog
 * @returns {Record<SlugKind, Map<string, SlugNamespace>>}
 */
function buildNamespaces(catalog) {
  /** @param {SlugKind} kind */
  const forKind = (kind) => new Map(MATCHUPS.map((m) => [m, buildNamespace(catalog, kind, m)]));
  return { builds: forKind("builds"), counters: forKind("counters") };
}

/** @type {ReadonlyArray<GuideCatalogEntry>} */
const GUIDE_CATALOG = Object.freeze(
  /** @type {GuideCatalogEntry[]} */ (GUIDE_CATALOG_JSON).map((entry) => Object.freeze({ ...entry })),
);

/** @type {ReadonlyMap<string, GuideCatalogEntry>} */
const CATALOG_BY_NAME = new Map(GUIDE_CATALOG.map((entry) => [entry.name, entry]));

const NAMESPACES = buildNamespaces(GUIDE_CATALOG);

/**
 * @param {SlugKind} kind
 * @param {string} matchup
 * @returns {SlugNamespace|null}
 */
function namespaceFor(kind, matchup) {
  return NAMESPACES[kind].get(matchup) || null;
}

/**
 * Catalog names in a matchup's builds namespace (sorted; empty for an
 * unknown matchup). This is the allowlist for guide `myBuild` values.
 *
 * Example: `buildNamesForMatchup("ZvP")` includes "ZvP - 2 Base Nydus" and
 * "Zerg - 8 Pool".
 *
 * @param {string} matchup "PvZ" form
 * @returns {ReadonlyArray<string>}
 */
function buildNamesForMatchup(matchup) {
  const ns = namespaceFor("builds", matchup);
  return ns ? ns.names : EMPTY_NAMES;
}

/**
 * Catalog names in a matchup's counters namespace — the allowlist for
 * `opponent.strategy` values in games the user played as `matchup`.
 *
 * Example: `strategyNamesForMatchup("PvZ")` includes "ZvP - Ling Bane Bust"
 * and "Zerg - 8 Pool"; `strategyNamesForMatchup("ZvP")` is "Protoss - …" only.
 *
 * @param {string} matchup "PvZ" form (the user's matchup)
 * @returns {ReadonlyArray<string>}
 */
function strategyNamesForMatchup(matchup) {
  const ns = namespaceFor("counters", matchup);
  return ns ? ns.names : EMPTY_NAMES;
}

/**
 * Slug of a build in a matchup's builds namespace.
 *
 * Example: `buildSlug("PvZ", "PvZ - Stargate into Glaives")` → "stargate-into-glaives".
 *
 * @param {string} matchup "PvZ" form
 * @param {string} name exact catalog name
 * @returns {string|null} null when the name is not a guide build of that matchup
 */
function buildSlug(matchup, name) {
  const ns = namespaceFor("builds", matchup);
  return (ns && ns.byName.get(name)) || null;
}

/**
 * Slug of an opponent strategy in a matchup's counters namespace.
 *
 * Example: `strategySlug("PvZ", "Zerg - 2 Base Nydus")` → "zerg-2-base-nydus".
 *
 * @param {string} matchup "PvZ" form (the user's matchup)
 * @param {string} name exact catalog name
 * @returns {string|null}
 */
function strategySlug(matchup, name) {
  const ns = namespaceFor("counters", matchup);
  return (ns && ns.byName.get(name)) || null;
}

/**
 * Page name of a guide, unique within its namespace: the display name,
 * suffixed with GENERIC_NAME_SUFFIX for the race-generic member of a
 * collision (the one whose slug carries the race prefix). Names outside
 * the namespace fall back to the plain display name.
 *
 * Example: `guideName("counters", "PvT", "Terran - Widow Mine Drop")` →
 * "Widow Mine Drop (any matchup)"; `guideName("counters", "PvT",
 * "TvP - Widow Mine Drop")` → "Widow Mine Drop".
 *
 * @param {SlugKind} kind
 * @param {string} matchup "PvZ" form (the user's matchup)
 * @param {string} name exact catalog name
 * @returns {string}
 */
function guideName(kind, matchup, name) {
  const base = displayName(name);
  const ns = namespaceFor(kind, matchup);
  const slug = ns ? ns.byName.get(name) : undefined;
  return slug && slug !== slugifyGuideText(base) ? `${base}${GENERIC_NAME_SUFFIX}` : base;
}

/**
 * True when `name` is a guide build (catalog opener) for `matchup`.
 *
 * @param {string} matchup "PvZ" form
 * @param {unknown} name
 * @returns {boolean}
 */
function isGuideBuildName(matchup, name) {
  return typeof name === "string" && buildSlug(matchup, name) !== null;
}

/**
 * True when `name` is a guide opponent strategy for the user's `matchup`.
 *
 * @param {string} matchup "PvZ" form
 * @param {unknown} name
 * @returns {boolean}
 */
function isGuideStrategyName(matchup, name) {
  return typeof name === "string" && strategySlug(matchup, name) !== null;
}

/**
 * Live slug an alias points at, or null.
 *
 * @param {AliasTable|undefined} aliases
 * @param {string} matchupSlugValue
 * @param {string} slug
 * @returns {string|null}
 */
function aliasTarget(aliases, matchupSlugValue, slug) {
  if (!aliases || !Object.hasOwn(aliases, matchupSlugValue)) return null;
  const table = aliases[matchupSlugValue];
  if (!table || !Object.hasOwn(table, slug)) return null;
  const target = table[slug];
  return typeof target === "string" ? target : null;
}

/**
 * Resolve a URL slug in one namespace: the live entry, a redirect for a
 * retired (aliased) slug, or null. Lookups are exact — URLs are canonical
 * lowercase, so "PvZ" / "Stargate-Into-Glaives" do not resolve.
 *
 * @param {SlugKind} kind
 * @param {unknown} matchupSlugValue e.g. "pvz"
 * @param {unknown} slug
 * @param {AliasTable|undefined} aliases
 * @returns {ResolvedSlug|SlugRedirect|null}
 */
function resolveSlug(kind, matchupSlugValue, slug, aliases) {
  const matchup = matchupFromSlug(matchupSlugValue);
  if (!matchup || typeof slug !== "string") return null;
  const ns = namespaceFor(kind, matchup);
  if (!ns) return null;
  const name = ns.bySlug.get(slug);
  if (name) return { matchup, name, slug };
  const mSlug = /** @type {string} */ (matchupSlugValue);
  const target = aliasTarget(aliases, mSlug, slug);
  if (target && ns.bySlug.has(target)) return { redirect: { matchupSlug: mSlug, slug: target } };
  return null;
}

/**
 * Resolve `/guides/<matchupSlug>/<slug>`.
 *
 * Example: `resolveBuild("zvp", "zerg-2-base-nydus")` →
 * `{ matchup: "ZvP", name: "Zerg - 2 Base Nydus", slug: "zerg-2-base-nydus" }`.
 *
 * @param {unknown} matchupSlugValue
 * @param {unknown} slug
 * @param {AliasTable} [aliases] alias table (defaults to SLUG_ALIASES.builds; tests inject one)
 * @returns {ResolvedSlug|SlugRedirect|null}
 */
function resolveBuild(matchupSlugValue, slug, aliases = SLUG_ALIASES.builds) {
  return resolveSlug("builds", matchupSlugValue, slug, aliases);
}

/**
 * Resolve `/guides/<matchupSlug>/counter/<slug>`.
 *
 * Example: `resolveStrategy("pvz", "ling-bane-bust")` →
 * `{ matchup: "PvZ", name: "ZvP - Ling Bane Bust", slug: "ling-bane-bust" }`.
 *
 * @param {unknown} matchupSlugValue
 * @param {unknown} slug
 * @param {AliasTable} [aliases] alias table (defaults to SLUG_ALIASES.counters; tests inject one)
 * @returns {ResolvedSlug|SlugRedirect|null}
 */
function resolveStrategy(matchupSlugValue, slug, aliases = SLUG_ALIASES.counters) {
  return resolveSlug("counters", matchupSlugValue, slug, aliases);
}

/**
 * Catalog row for an exact catalog name (openers and non-openers).
 *
 * Example: `catalogEntry("Zerg - 8 Pool").race` → "Zerg".
 *
 * @param {unknown} name
 * @returns {GuideCatalogEntry|null}
 */
function catalogEntry(name) {
  if (typeof name !== "string") return null;
  return CATALOG_BY_NAME.get(name) || null;
}

/**
 * URL slug of a map name (same rule on the full name, suffix included).
 *
 * Example: `mapSlug("Alcyone LE")` → "alcyone-le".
 *
 * @param {unknown} mapName
 * @returns {string|null} null when the name has no ASCII letters/digits
 */
function mapSlug(mapName) {
  if (typeof mapName !== "string") return null;
  return slugifyGuideText(mapName) || null;
}

/**
 * @param {[string, string]} a
 * @param {[string, string]} b
 * @returns {number}
 */
function compareFirst(a, b) {
  if (a[0] < b[0]) return -1;
  return a[0] > b[0] ? 1 : 0;
}

/**
 * The live mapping, shaped like `guideSlugs.lock.json`:
 * `{ builds: { pvz: { slug: name } }, counters: { pvz: { slug: name } } }`
 * with slugs sorted. Returns a fresh object each call.
 *
 * @returns {Record<SlugKind, SlugNamespaceTable>}
 */
function guideSlugTable() {
  /** @type {Record<SlugKind, SlugNamespaceTable>} */
  const table = { builds: {}, counters: {} };
  for (const kind of SLUG_KINDS) {
    for (const matchup of MATCHUPS) {
      const ns = /** @type {SlugNamespace} */ (namespaceFor(kind, matchup));
      table[kind][matchup.toLowerCase()] = Object.fromEntries([...ns.bySlug].sort(compareFirst));
    }
  }
  return table;
}

/**
 * Problems with an alias table: unknown matchup slugs, aliases shadowed by
 * a live slug (unreachable) and targets that are not live slugs.
 *
 * @param {Readonly<Record<SlugKind, AliasTable>>} aliases
 * @returns {string[]} empty when valid
 */
function validateSlugAliases(aliases) {
  /** @type {string[]} */
  const problems = [];
  for (const kind of SLUG_KINDS) {
    for (const [mSlug, table] of Object.entries(aliases[kind] || {})) {
      const matchup = matchupFromSlug(mSlug);
      const ns = matchup ? namespaceFor(kind, matchup) : null;
      if (!ns) {
        problems.push(`${kind}: unknown matchup slug "${mSlug}"`);
        continue;
      }
      for (const [from, to] of Object.entries(table)) {
        if (ns.bySlug.has(from)) problems.push(`${kind}/${mSlug}: "${from}" is a live slug`);
        if (!ns.bySlug.has(to)) problems.push(`${kind}/${mSlug}: target "${to}" is not a live slug`);
      }
    }
  }
  return problems;
}

const ALIAS_PROBLEMS = validateSlugAliases(SLUG_ALIASES);
if (ALIAS_PROBLEMS.length > 0) {
  throw new Error(`guideSlugs: invalid SLUG_ALIASES: ${ALIAS_PROBLEMS.join("; ")}`);
}

module.exports = {
  GUIDE_CATALOG,
  MATCHUPS,
  RACE_WORDS,
  SLUG_ALIASES,
  SLUG_MAX_CHARS,
  slugifyGuideText,
  displayName,
  guideName,
  matchupSlug,
  matchupFromSlug,
  buildNamesForMatchup,
  strategyNamesForMatchup,
  buildSlug,
  strategySlug,
  isGuideBuildName,
  isGuideStrategyName,
  resolveBuild,
  resolveStrategy,
  catalogEntry,
  mapSlug,
  guideSlugTable,
  validateSlugAliases,
};
