"use client";

import { useMemo, useRef, useState } from "react";
import Link from "next/link";
import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronDown,
  Copy,
  FileUp,
  Loader2,
  Sparkles,
  Upload,
} from "lucide-react";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { Modal } from "@/components/ui/Modal";
import { API_BASE } from "@/lib/clientApi";
import { BuildEditorModal } from "@/components/builds/editor";
import {
  normalizeBuildName,
  type BuildOrderEvent,
} from "@/lib/build-events";
import type { RaceLite, VsRaceLite } from "@/lib/build-rules";

/* eslint-disable max-lines */
/**
 * ReplayDemo — landing-page "drop a replay, see the real dossier" CTA.
 *
 * The demo runs a real parse on the server: when the visitor picks a
 * file, we POST the binary to /v1/public/preview-replay (an unauth'd
 * rate-limited route backed by sc2reader). The route returns both
 * players' identity, race, result, and build log.
 *
 * On success we open the rich BuildEditorModal in demoMode so the
 * visitor can experience the real "Save as new build" template:
 * source-replay timeline, rule promotion, basics editing, strategy
 * notes — everything except the actual save (which is gated behind
 * sign-up). This is closer to what they'll actually do once signed
 * in than the read-only dossier we used to ship here.
 *
 * No mock data — if the upload fails, we surface the failure and a
 * sign-up CTA instead of pretending we know what's in the file.
 */

interface PreviewPlayer {
  name: string;
  race: string;
  result: string;
  handle: string | null;
  build_log: string[];
  mmr?: number;
}

interface PreviewDossier {
  ok: true;
  game_id: string;
  map: string;
  duration_sec: number;
  date: string;
  players: [PreviewPlayer, PreviewPlayer];
}

interface PreviewError {
  code: string;
  message: string;
  /** Server-assigned correlation ID (`x-request-id` response header
   *  or `error.requestId` body field). Surfaced in the modal's
   *  technical-details disclosure so a user can paste it into a bug
   *  report and we can grep the server logs for the same trace. */
  requestId?: string;
  /** HTTP status code returned by the API. Recorded so the
   *  technical-details disclosure can show e.g. "HTTP 502" alongside
   *  the application-level code, since they encode different things
   *  (transport vs domain). */
  httpStatus?: number;
}

const MAX_BYTES = 5 * 1024 * 1024; // matches the API limit
const FRIENDLY_ERRORS: Record<string, string> = {
  empty_body: "That file looked empty — pick another replay?",
  not_a_replay:
    "That doesn't look like a .SC2Replay file. Pick a real replay from your StarCraft II folder.",
  no_two_humans:
    "This demo only handles 1v1 replays with two human players (no vs-AI / co-op).",
  ai_game: "This demo only handles 1v1 vs another human, not vs-AI.",
  parser_no_output: "The parser ran but returned nothing. Try a different replay.",
  python_error: "The cloud parser hit an error on this replay. Try a different one.",
  parse_failed: "Couldn't parse that replay. Try a different one.",
  replay_too_new:
    "This replay was generated by an SC2 patch newer than our public demo can read. Sign up — the desktop agent updates with each patch and will parse it.",
  parser_import_failed:
    "The cloud preview is misconfigured. Sign up and the desktop agent will still parse this replay.",
  extract_failed:
    "We loaded the replay but couldn't walk its event stream. Try a different replay.",
  file_not_found:
    "We lost track of the upload before parsing it. Try the upload again.",
  preview_timeout:
    "The cloud preview timed out on this replay. Sign up and the desktop agent will parse it without the 30-second cap.",
  parser_overflow:
    "This replay is too large for the live demo. Sign up and the agent will handle it.",
  preview_unavailable:
    "The live preview is temporarily offline. Sign up and your real replays will still parse.",
  rate_limited: "Easy! Wait a minute then try another replay.",
  too_large: "That file is bigger than the demo accepts. Pick a smaller one or sign up.",
};

export function ReplayDemo() {
  const inputRef = useRef<HTMLInputElement>(null);
  const [busy, setBusy] = useState(false);
  const [filename, setFilename] = useState<string | null>(null);
  const [dossier, setDossier] = useState<PreviewDossier | null>(null);
  const [error, setError] = useState<PreviewError | null>(null);
  const [statusOpen, setStatusOpen] = useState(false);
  const [editorOpen, setEditorOpen] = useState(false);
  // Which player's build the editor is seeded with. Default to the
  // first player (index 0) — the visitor can swap sides via the
  // floating perspective chip rendered above the modal scrim.
  const [perspective, setPerspective] = useState<0 | 1>(0);

  const me = dossier?.players[perspective] ?? null;
  const opp = dossier?.players[perspective === 0 ? 1 : 0] ?? null;
  const editorEvents = useMemo(
    () => (me ? buildLogToEvents(me.build_log, me.race) : []),
    [me],
  );
  const editorRace: RaceLite = coerceRace(me?.race);
  const editorVsRace: VsRaceLite = coerceVsRace(opp?.race);

  async function onPick(file: File | null) {
    if (!file) return;
    setFilename(file.name);
    setDossier(null);
    setError(null);
    setEditorOpen(false);
    setPerspective(0);
    setStatusOpen(true);
    if (file.size === 0) {
      setError({ code: "empty_body", message: "" });
      return;
    }
    if (file.size > MAX_BYTES) {
      setError({ code: "too_large", message: "" });
      return;
    }
    setBusy(true);
    try {
      const buf = await file.arrayBuffer();
      const res = await fetch(`${API_BASE}/v1/public/preview-replay`, {
        method: "POST",
        headers: { "content-type": "application/octet-stream" },
        body: buf,
      });
      const requestId =
        res.headers.get("x-request-id") || undefined;
      const json = await res.json().catch(() => null);
      if (!res.ok || !json) {
        const code = json?.error?.code || `http_${res.status}`;
        const message = json?.error?.message || "";
        setError({
          code,
          message,
          requestId: json?.error?.requestId || requestId,
          httpStatus: res.status,
        });
        return;
      }
      if (json.ok !== true) {
        setError({
          code: json.error?.code || "parse_failed",
          message: json.error?.message || "",
          requestId: json.error?.requestId || requestId,
          httpStatus: res.status,
        });
        return;
      }
      setDossier(json as PreviewDossier);
      // Hand off from the small status modal to the rich save-as-new-build
      // template. The editor opens with the parsed events seeded into
      // its source-replay column.
      setStatusOpen(false);
      setEditorOpen(true);
    } catch (err) {
      const message = err instanceof Error ? err.message : "network error";
      setError({ code: "network", message });
    } finally {
      setBusy(false);
    }
  }

  return (
    <section className="mx-auto max-w-5xl">
      <Card padded={false} className="overflow-hidden">
        <div className="grid items-center gap-6 p-6 md:grid-cols-[minmax(0,1.1fr)_minmax(0,1fr)] md:gap-10 md:p-10">
          <div className="space-y-4">
            <Badge
              variant="cyan"
              iconLeft={<Sparkles className="h-3.5 w-3.5" aria-hidden />}
            >
              Try it on a real replay
            </Badge>
            <h2 className="text-h2 font-semibold text-text md:text-h1">
              Drop a <span className="text-accent-cyan">.SC2Replay</span> file —
              build a custom build from it.
            </h2>
            <p className="text-body-lg text-text-muted">
              Pick any replay from your StarCraft II folder. We&rsquo;ll parse
              it on the spot, then drop you straight into the
              save-as-new-build template — promote starred events into rules,
              tweak the basics, and feel the real workflow before you sign up.
            </p>
            <div className="flex flex-wrap gap-3 pt-1">
              <Button
                variant="primary"
                size="lg"
                onClick={() => inputRef.current?.click()}
                iconLeft={<Upload className="h-5 w-5" aria-hidden />}
              >
                Choose a replay
              </Button>
              <input
                ref={inputRef}
                type="file"
                accept=".SC2Replay"
                className="sr-only"
                onChange={(e) => void onPick(e.target.files?.[0] ?? null)}
              />
              <Link
                href="/sign-up"
                className="inline-flex h-12 min-w-[44px] items-center justify-center gap-2 rounded-lg border border-border bg-bg-elevated px-5 text-body-lg font-semibold text-text hover:bg-bg-subtle hover:border-border-strong focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent focus-visible:ring-offset-2 focus-visible:ring-offset-bg"
              >
                Skip the demo
                <ArrowRight className="h-5 w-5" aria-hidden />
              </Link>
            </div>
            <p className="text-caption text-text-dim">
              Files are parsed once and discarded — nothing about your replay
              is stored.
            </p>
          </div>

          <ReplayDropPreview onActivate={() => inputRef.current?.click()} />
        </div>
      </Card>

      <Modal
        open={statusOpen}
        onClose={() => setStatusOpen(false)}
        size="lg"
        title={
          <span className="flex flex-wrap items-center gap-2">
            <span className="text-h4 font-semibold text-text">
              {busy ? "Parsing replay…" : "Replay preview"}
            </span>
            {filename ? (
              <Badge variant="cyan" size="sm">
                {filename.length > 36
                  ? `${filename.slice(0, 33)}…`
                  : filename}
              </Badge>
            ) : null}
          </span>
        }
        description={
          busy
            ? "Parsing your replay on the cloud preview server…"
            : error
              ? "Something didn't work."
              : "Pick a replay above to see it parsed live."
        }
      >
        {busy ? (
          <DossierLoading />
        ) : error ? (
          <DossierError error={error} />
        ) : (
          <DossierLoading />
        )}
      </Modal>

      <BuildEditorModal
        open={editorOpen && !!dossier}
        onClose={() => setEditorOpen(false)}
        events={editorEvents}
        gameId={dossier?.game_id}
        race={editorRace}
        vsRace={editorVsRace}
        perspective="you"
        defaultName={defaultBuildName(me, opp)}
        demoMode
      />

      {dossier && editorOpen ? (
        <PerspectiveSwitcherToast
          dossier={dossier}
          perspective={perspective}
          onSelect={setPerspective}
        />
      ) : null}
    </section>
  );
}

/* ---------------- Demo helpers ---------------- */

/**
 * Convert the public preview's `[m:ss] EventName` build-log strings
 * into BuildOrderEvent records the BuildEditor's source-timeline
 * column understands. We don't have category/is_building hints from
 * the public CLI, so we run each name through normalizeBuildName to
 * recover them.
 */
function buildLogToEvents(
  buildLog: ReadonlyArray<string>,
  race: string | undefined,
): BuildOrderEvent[] {
  const events: BuildOrderEvent[] = [];
  for (const line of buildLog) {
    const m = /^\[(\d+):(\d{2})\]\s+(.+?)\s*$/.exec(line);
    if (!m) continue;
    const minutes = parseInt(m[1], 10);
    const seconds = parseInt(m[2], 10);
    if (!Number.isFinite(minutes) || !Number.isFinite(seconds)) continue;
    const time = minutes * 60 + seconds;
    const name = m[3];
    if (!name) continue;
    const norm = normalizeBuildName(name);
    const cat: BuildOrderEvent["category"] | undefined =
      norm.category === "other" ? undefined : norm.category;
    events.push({
      time,
      name,
      time_display: `${minutes}:${seconds.toString().padStart(2, "0")}`,
      display: norm.displayName,
      category: cat,
      is_building: norm.category === "building",
      race,
    });
  }
  return events;
}

function coerceRace(r: string | undefined): RaceLite {
  if (r === "Protoss" || r === "Terran" || r === "Zerg" || r === "Random") {
    return r;
  }
  return "Random";
}

function coerceVsRace(r: string | undefined): VsRaceLite {
  if (
    r === "Protoss" ||
    r === "Terran" ||
    r === "Zerg" ||
    r === "Random" ||
    r === "Any"
  ) {
    return r;
  }
  return "Any";
}

function defaultBuildName(
  me: PreviewPlayer | null,
  opp: PreviewPlayer | null,
): string | undefined {
  if (!me || !opp) return undefined;
  const a = me.race?.charAt(0).toUpperCase() || "?";
  const b = opp.race?.charAt(0).toUpperCase() || "?";
  return `${a}v${b} — Custom`;
}

/**
 * Floating chip rendered alongside the BuildEditor demo modal so the
 * visitor can flip between which player's build the editor is seeded
 * with. Positioned at the top of the viewport so it sits above the
 * modal scrim without competing with the editor's own header.
 */
function PerspectiveSwitcherToast({
  dossier,
  perspective,
  onSelect,
}: {
  dossier: PreviewDossier;
  perspective: 0 | 1;
  onSelect: (next: 0 | 1) => void;
}) {
  return (
    <div className="pointer-events-none fixed inset-x-0 top-3 z-[60] flex justify-center px-3">
      <div className="pointer-events-auto flex items-center gap-2 rounded-full border border-border bg-bg-elevated/95 px-3 py-1.5 text-caption text-text-muted shadow-lg backdrop-blur">
        <span className="hidden sm:inline">Editing build for:</span>
        {dossier.players.map((p, i) => {
          const isActive = perspective === i;
          return (
            <button
              key={p.handle ?? `p${i}`}
              type="button"
              onClick={() => onSelect(i as 0 | 1)}
              aria-pressed={isActive}
              className={[
                "inline-flex items-center gap-1 rounded-full px-3 py-1 font-medium",
                "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent",
                isActive
                  ? "bg-accent-cyan/20 text-accent-cyan"
                  : "text-text-muted hover:bg-bg-subtle hover:text-text",
              ].join(" ")}
            >
              <span>{p.name}</span>
              <span className="text-text-dim">· {p.race}</span>
            </button>
          );
        })}
      </div>
    </div>
  );
}

function DossierLoading() {
  return (
    <div className="flex items-center justify-center gap-3 py-12 text-text-muted">
      <Loader2 className="h-5 w-5 animate-spin text-accent-cyan" aria-hidden />
      <span className="text-body">Parsing replay…</span>
    </div>
  );
}

function DossierError({ error }: { error: PreviewError }) {
  const friendly = FRIENDLY_ERRORS[error.code] || error.message ||
    "We couldn't parse that replay.";
  return (
    <div className="space-y-4 py-4">
      <div className="flex items-start gap-3 rounded-lg border border-danger/40 bg-danger/10 p-4 text-body text-danger">
        <AlertTriangle className="mt-0.5 h-5 w-5 flex-shrink-0" aria-hidden />
        <div className="space-y-1">
          <p className="font-medium">Couldn&apos;t parse that replay</p>
          <p className="text-text-muted">{friendly}</p>
        </div>
      </div>
      <ErrorTechnicalDetails error={error} />
      <p className="text-caption text-text-muted">
        Sign up and the agent will parse every replay automatically — even
        the ones the public demo can&rsquo;t handle.
      </p>
    </div>
  );
}

/**
 * Collapsible "Show technical details" disclosure for the error
 * modal. Surfaces the application-level code, raw error message,
 * HTTP status, and server-assigned request ID — plus a copy button
 * that lays it all out as a one-line plaintext blob suitable for
 * pasting into a bug report or chat.
 *
 * Why this exists: the friendly message tells the visitor what to do
 * next, but it deliberately doesn't expose internals. When something
 * is wrong with the cloud parser itself (vs. a quirky replay), the
 * fastest path to a fix is the user pasting us the request ID so we
 * can grep the Render logs for the matching trace. Hiding it behind
 * a disclosure keeps the friendly path uncluttered while making the
 * diagnostic path one click away.
 */
function ErrorTechnicalDetails({ error }: { error: PreviewError }) {
  const [open, setOpen] = useState(false);
  const [copied, setCopied] = useState(false);

  const lines: string[] = [`code: ${error.code}`];
  if (typeof error.httpStatus === "number") {
    lines.push(`http: ${error.httpStatus}`);
  }
  if (error.requestId) {
    lines.push(`request_id: ${error.requestId}`);
  }
  if (error.message) {
    lines.push(`message: ${error.message}`);
  }
  lines.push(`time: ${new Date().toISOString()}`);
  const blob = lines.join("\n");

  async function onCopy() {
    try {
      await navigator.clipboard.writeText(blob);
      setCopied(true);
      window.setTimeout(() => setCopied(false), 1600);
    } catch {
      // Clipboard can fail in restricted iframes; silently no-op.
    }
  }

  return (
    <div className="rounded-lg border border-border bg-bg-elevated/40">
      <button
        type="button"
        onClick={() => setOpen((prev) => !prev)}
        aria-expanded={open}
        className="flex w-full items-center justify-between gap-2 rounded-lg px-3 py-2 text-caption font-medium text-text-muted hover:text-text focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent"
      >
        <span className="flex items-center gap-2">
          <ChevronDown
            className={`h-3.5 w-3.5 transition-transform motion-safe:duration-150 ${
              open ? "rotate-0" : "-rotate-90"
            }`}
            aria-hidden
          />
          Show technical details
        </span>
        <span className="font-mono text-text-dim">{error.code}</span>
      </button>
      {open ? (
        <div className="space-y-2 border-t border-border px-3 py-3">
          <dl className="grid grid-cols-[auto_minmax(0,1fr)] gap-x-3 gap-y-1 font-mono text-caption">
            <dt className="text-text-dim">code</dt>
            <dd className="break-all text-text">{error.code}</dd>
            {typeof error.httpStatus === "number" ? (
              <>
                <dt className="text-text-dim">http</dt>
                <dd className="text-text">{error.httpStatus}</dd>
              </>
            ) : null}
            {error.requestId ? (
              <>
                <dt className="text-text-dim">request_id</dt>
                <dd className="break-all text-text">{error.requestId}</dd>
              </>
            ) : null}
            {error.message ? (
              <>
                <dt className="text-text-dim">message</dt>
                <dd className="break-all text-text">{error.message}</dd>
              </>
            ) : null}
          </dl>
          <button
            type="button"
            onClick={() => void onCopy()}
            className="inline-flex h-8 items-center gap-1.5 rounded-md border border-border bg-bg-surface px-2.5 text-caption font-medium text-text-muted hover:bg-bg-subtle hover:text-text focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent"
          >
            {copied ? (
              <>
                <Check className="h-3.5 w-3.5 text-success" aria-hidden />
                Copied
              </>
            ) : (
              <>
                <Copy className="h-3.5 w-3.5" aria-hidden />
                Copy details
              </>
            )}
          </button>
        </div>
      ) : null}
    </div>
  );
}

function ReplayDropPreview({ onActivate }: { onActivate: () => void }) {
  return (
    <button
      type="button"
      onClick={onActivate}
      aria-label="Choose a replay file to preview"
      className="group relative flex aspect-[4/3] w-full flex-col items-center justify-center gap-4 overflow-hidden rounded-xl border border-dashed border-accent-cyan/40 bg-bg-elevated/40 p-6 text-center transition-colors hover:border-accent-cyan focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent focus-visible:ring-offset-2 focus-visible:ring-offset-bg"
    >
      <span
        aria-hidden
        className="pointer-events-none absolute inset-0 opacity-70"
        style={{
          background:
            "radial-gradient(ellipse at center, var(--halo-cyan) 0%, transparent 70%)",
        }}
      />
      <span
        aria-hidden
        className="relative flex h-16 w-16 items-center justify-center rounded-2xl border border-accent-cyan/40 bg-accent-cyan/10 text-accent-cyan motion-safe:transition-transform motion-safe:duration-200 group-hover:scale-110"
      >
        <FileUp className="h-8 w-8" />
      </span>
      <span className="relative space-y-1">
        <span className="block text-h4 font-semibold text-text">
          Pick a replay
        </span>
        <span className="block text-caption text-text-muted">
          .SC2Replay · parsed live, never stored
        </span>
      </span>
    </button>
  );
}

