// Shape of the live-payload the agent broadcasts to the overlay
// socket room. Matches `apps/agent/sc2tools_agent/replay_pipeline.py`.
//
// Two distinct envelope shapes flow through this file:
//
//   * ``LiveGamePayload`` — the legacy/post-game shape. Built by the
//     cloud's ``OverlayLiveService.buildFromGame`` from a finished
//     game's replay-derived data and broadcast on the
//     ``overlay:live`` Socket.io event.
//   * ``LiveGameEnvelope`` — the pre-game / in-game shape. Emitted
//     by the desktop agent (see
//     ``apps/agent/sc2tools_agent/live/types.py#envelope_for``),
//     POSTed to ``/v1/agent/live``, and fanned out by the cloud's
//     ``LiveGameBroker`` on the ``overlay:liveGame`` Socket.io event
//     (and the ``GET /v1/me/live`` SSE stream).
//
// They co-exist by design: when both have data for the same gameKey,
// the post-game ``LiveGamePayload`` wins because it carries the
// authoritative replay-derived fields (build, durationSec, etc.).

export type LiveGamePayload = {
  /**
   * Set when the payload was generated by the Settings → Overlay Test
   * button rather than a real game. The overlay clients use this to
   * cap *every* widget — including the normally-persistent ones — at
   * a short duration so a Test fire never sits on the streamer's
   * scene.
   */
  isTest?: boolean;
  /**
   * Stable per-game identifier — same value the agent's pre-game
   * envelope carries on ``LiveGameEnvelope.gameKey``. The cloud
   * stamps it on every post-game payload it derives so the overlay
   * client can detect "live envelope's gameKey just changed → drop
   * cached post-game data" via
   * ``useClearStalePostGameOnGameKeyChange``. The fall-back when no
   * agent envelope was observed (agent offline at game-start, batch
   * historical re-upload) is the cloud's own ``gameId`` — still
   * unique per game, just not name-derivable.
   */
  gameKey?: string;
  /** Player race ("Terran", "Zerg", "Protoss", "Random"). */
  myRace?: string;
  /** Opponent race. */
  oppRace?: string;
  /** Opponent display name (battle tag without #1234 disambiguator). */
  oppName?: string;
  /** Map name. */
  map?: string;
  /** Matchup label, e.g. "PvT". */
  matchup?: string;
  /** Result of the just-finished game. */
  result?: "win" | "loss" | null;
  /** Game length in seconds. */
  durationSec?: number;
  /** Opponent MMR if known. */
  oppMmr?: number;
  /** Player MMR if known. */
  myMmr?: number;
  /** MMR delta from this game (signed). */
  mmrDelta?: number;
  /** Head-to-head record vs this opponent. */
  headToHead?: { wins: number; losses: number };
  /** Current win/loss streak. */
  streak?: { kind: "win" | "loss"; count: number };
  /** Cheese-likelihood score (0..1). */
  cheeseProbability?: number;
  /** Predicted opponent strategies. */
  predictedStrategies?: { name: string; weight: number }[];
  /** Top builds the player likes vs this matchup. */
  topBuilds?: { name: string; total: number; winRate: number }[];
  /** Best answer vs this opponent's most-likely opening. */
  bestAnswer?: { build: string; winRate: number; total: number } | null;
  /** Favorite opening this opponent has shown. */
  favOpening?: { name: string; share: number; samples: number } | null;
  /** Scouting tells. */
  scouting?: { label: string; tellAt?: number; confidence?: number }[];
  /**
   * Last N games vs the current opponent in this matchup. Drives the
   * scouting card's "LAST GAMES" list — same data the legacy SPA pulled
   * from `meta_database.json` to render "result · length · map · YOU
   * vs OPP build". Newest first.
   */
  recentGames?: Array<{
    /** "Win" | "Loss" | "Tie" — uppercased for the result-chip text. */
    result: "Win" | "Loss" | "Tie";
    /** Duration as `m:ss`, pre-formatted so the widget stays markup-only. */
    lengthText: string;
    /** Map name, e.g. "Goldenaura LE". */
    map?: string;
    /** Player's classified build, e.g. "PvZ - 3 Stargate Phoenix". */
    myBuild?: string;
    /** Opponent's classified strategy, e.g. "Zerg - 3 Base Macro (Hatch First)". */
    oppBuild?: string;
    /** Opponent race for the matchup label / icon, when known. */
    oppRace?: string;
    /** ISO date string of the game, used as the row key. */
    date?: string;
  }>;
  /** Session record (today). */
  session?: {
    wins: number;
    losses: number;
    games: number;
    mmrStart?: number;
    mmrCurrent?: number;
    /** SC2Pulse region label (e.g. "NA", "EU"). */
    region?: string;
    /**
     * Earliest game in today's session, ISO date. The SessionWidget uses
     * this to render the "Xm" elapsed-time stamp the SPA shows.
     */
    sessionStartedAt?: string;
    /** Current win/loss run, if 2+. Drives the streak chip. */
    streak?: { kind: "win" | "loss"; count: number };
  };
  /** Player rank info. */
  rank?: { league?: string; tier?: number; mmr?: number };
  /** Meta — current ladder snapshot. */
  meta?: { matchup?: string; topBuilds?: { name: string; share: number }[] };
  /** Rivalry context. */
  rival?: {
    name?: string;
    headToHead?: { wins: number; losses: number };
    note?: string;
  };
  /** Rematch flag. */
  rematch?: { isRematch: boolean; lastResult?: "win" | "loss" } | null;
};

/**
 * Lifecycle phase the agent's bridge currently considers the user to
 * be in. Matches ``LiveLifecyclePhase`` in
 * ``apps/agent/sc2tools_agent/live/types.py``.
 */
export type LiveGamePhase =
  | "idle"
  | "menu"
  | "match_loading"
  | "match_started"
  | "match_in_progress"
  | "match_ended";

/**
 * Single player entry inside the agent's envelope. Mirrors
 * ``LivePlayer`` in the agent's types, post-``to_jsonable`` so values
 * are plain JSON tokens.
 */
export interface LiveGameEnvelopePlayer {
  name: string;
  /** ``"user"`` (human) or ``"computer"`` (AI). */
  type: string;
  /** ``"Terran" | "Zerg" | "Protoss" | "random"`` and friends. */
  race: string;
  /** ``"Undecided" | "Victory" | "Defeat" | "Tie"``. */
  result: string;
  player_id?: number | null;
}

/**
 * SC2Pulse-resolved opponent profile. Field names use snake_case
 * because the agent serialises ``OpponentProfile`` via
 * ``dataclasses.asdict`` which preserves the Python attribute names
 * verbatim (no camelCase conversion). Mirror that here so consumers
 * don't have to second-guess what the wire actually carries.
 */
export interface LiveGameEnvelopeProfile {
  pulse_character_id?: number | null;
  region?: string | null;
  battle_tag?: string | null;
  account_handle?: string | null;
  mmr?: number | null;
  league?: string | null;
  league_tier?: number | null;
  top_race?: string | null;
  recent_games_count?: number | null;
  /** 0..1 — the bridge's confidence the resolver picked the right candidate. */
  confidence?: number;
  alternatives?: string[];
  resolved_at?: number;
}

/**
 * Wire shape produced by the desktop agent's ``envelope_for()`` and
 * enriched by ``LiveBridge`` with the resolved opponent profile.
 *
 * Stays intentionally flat so widgets can read fields without a
 * schema lib. Every property is optional — partial-failure paths
 * (Pulse 502, ambiguous name, the very first envelope at
 * ``match_loading`` before Pulse responds) all flow through the same
 * ``LiveGameEnvelope`` shape, just with fewer fields populated.
 *
 * **Privacy note (per spec):** the ``user`` block carries only the
 * streamer's display name (no Pulse handle, no MMR). Opponent data
 * lives under ``opponent`` and is the only Pulse-resolved field set
 * on the envelope.
 */
export interface LiveGameEnvelope {
  type: "liveGameState";
  phase: LiveGamePhase;
  /** Wall-clock timestamp the agent stamped on capture (seconds since epoch). */
  capturedAt: number;
  /**
   * Wall-clock timestamp the cloud stamped on receipt
   * (milliseconds since epoch). Set by ``routes/agentLive.js`` —
   * useful for the dashboard's "Last seen Xs ago" indicator.
   */
  receivedAt?: number;
  /** Stable per-game identifier — sorted player names + match-start ms. */
  gameKey?: string;
  /**
   * ``true`` when this envelope was synthesised by the cloud rather
   * than the agent's poll loop. The ``LiveGameBroker`` emits a
   * synthetic ``match_loading`` prelude on overlay
   * connect / ``overlay:resync`` when the cached state is past the
   * loading screen, so the client's gameKey-change effect always has
   * a chance to clear stale ``live`` even when the original
   * loading event was lost to a disconnect or page reload.
   * Telemetry-only — widgets render the same regardless.
   */
  synthetic?: boolean;
  /** Seconds elapsed in the SC2 client's in-game clock. */
  displayTime?: number;
  /** True when the user is watching a replay (the bridge ignores these). */
  isReplay?: boolean;
  /** Raw activeScreens list from /ui — diagnostics only. */
  uiScreens?: string[];
  /** Raw player list from /game. */
  players?: LiveGameEnvelopePlayer[];
  /**
   * Bridge-derived opponent. Populated from the moment ``match_loading``
   * fires; the ``profile`` sub-object lands a few hundred ms later
   * once Pulse responds (or stays absent if Pulse is down).
   */
  opponent?: {
    name?: string | null;
    race?: string | null;
    profile?: LiveGameEnvelopeProfile;
  };
  /** Streamer's own name — purely cosmetic, never used for auth. */
  user?: { name?: string | null };
  /**
   * Cloud-side enrichment: the streamer's history with this opponent,
   * pulled from the cloud's games + opponents collections by the
   * ``LiveGameBroker``'s enrich hook before fan-out. Carries the same
   * fields the post-game ``LiveGamePayload`` does for the relevant
   * "who is this opponent and what's our shared history" widgets —
   * head-to-head, recent games (with build labels), RIVAL/FAMILIAR
   * tier, best-answer, cheese probability, predicted strategies.
   *
   * Result-specific fields (``result``, ``durationSec``, ``mmrDelta``,
   * ``map``) are deliberately absent — those only land post-game when
   * the replay parses.
   */
  streamerHistory?: Pick<
    LiveGamePayload,
    | "myRace"
    | "oppRace"
    | "oppName"
    | "oppMmr"
    | "matchup"
    | "headToHead"
    | "streak"
    | "cheeseProbability"
    | "predictedStrategies"
    | "topBuilds"
    | "bestAnswer"
    | "favOpening"
    | "scouting"
    | "recentGames"
    | "rank"
    | "meta"
    | "rival"
    | "rematch"
  >;
}
