// Shape of the live-payload the agent broadcasts to the overlay
// socket room. Matches `apps/agent/sc2tools_agent/replay_pipeline.py`.

export type LiveGamePayload = {
  /**
   * Set when the payload was generated by the Settings → Overlay Test
   * button rather than a real game. The overlay clients use this to
   * cap *every* widget — including the normally-persistent ones — at
   * a short duration so a Test fire never sits on the streamer's
   * scene.
   */
  isTest?: boolean;
  /** Player race ("Terran", "Zerg", "Protoss", "Random"). */
  myRace?: string;
  /** Opponent race. */
  oppRace?: string;
  /** Opponent display name (battle tag without #1234 disambiguator). */
  oppName?: string;
  /** Map name. */
  map?: string;
  /** Matchup label, e.g. "PvT". */
  matchup?: string;
  /** Result of the just-finished game. */
  result?: "win" | "loss" | null;
  /** Game length in seconds. */
  durationSec?: number;
  /** Opponent MMR if known. */
  oppMmr?: number;
  /** Player MMR if known. */
  myMmr?: number;
  /** MMR delta from this game (signed). */
  mmrDelta?: number;
  /** Head-to-head record vs this opponent. */
  headToHead?: { wins: number; losses: number };
  /** Current win/loss streak. */
  streak?: { kind: "win" | "loss"; count: number };
  /** Cheese-likelihood score (0..1). */
  cheeseProbability?: number;
  /** Predicted opponent strategies. */
  predictedStrategies?: { name: string; weight: number }[];
  /** Top builds the player likes vs this matchup. */
  topBuilds?: { name: string; total: number; winRate: number }[];
  /** Best answer vs this opponent's most-likely opening. */
  bestAnswer?: { build: string; winRate: number; total: number } | null;
  /** Favorite opening this opponent has shown. */
  favOpening?: { name: string; share: number; samples: number } | null;
  /** Scouting tells. */
  scouting?: { label: string; tellAt?: number; confidence?: number }[];
  /**
   * Last N games vs the current opponent in this matchup. Drives the
   * scouting card's "LAST GAMES" list — same data the legacy SPA pulled
   * from `meta_database.json` to render "result · length · map · YOU
   * vs OPP build". Newest first.
   */
  recentGames?: Array<{
    /** "Win" | "Loss" | "Tie" — uppercased for the result-chip text. */
    result: "Win" | "Loss" | "Tie";
    /** Duration as `m:ss`, pre-formatted so the widget stays markup-only. */
    lengthText: string;
    /** Map name, e.g. "Goldenaura LE". */
    map?: string;
    /** Player's classified build, e.g. "PvZ - 3 Stargate Phoenix". */
    myBuild?: string;
    /** Opponent's classified strategy, e.g. "Zerg - 3 Base Macro (Hatch First)". */
    oppBuild?: string;
    /** Opponent race for the matchup label / icon, when known. */
    oppRace?: string;
    /** ISO date string of the game, used as the row key. */
    date?: string;
  }>;
  /** Session record (today). */
  session?: {
    wins: number;
    losses: number;
    games: number;
    mmrStart?: number;
    mmrCurrent?: number;
    /** SC2Pulse region label (e.g. "NA", "EU"). */
    region?: string;
    /**
     * Earliest game in today's session, ISO date. The SessionWidget uses
     * this to render the "Xm" elapsed-time stamp the SPA shows.
     */
    sessionStartedAt?: string;
    /** Current win/loss run, if 2+. Drives the streak chip. */
    streak?: { kind: "win" | "loss"; count: number };
  };
  /** Player rank info. */
  rank?: { league?: string; tier?: number; mmr?: number };
  /** Meta — current ladder snapshot. */
  meta?: { matchup?: string; topBuilds?: { name: string; share: number }[] };
  /** Rivalry context. */
  rival?: {
    name?: string;
    headToHead?: { wins: number; losses: number };
    note?: string;
  };
  /** Rematch flag. */
  rematch?: { isRematch: boolean; lastResult?: "win" | "loss" } | null;
};
